# Generated by Django 6.1.1 on 2026-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Student Name'),
        ),
    ]
