# Generated by Django 6.1.1 on 2026-09-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_alter_stu_m_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stu_m',
            new_name='stu_Model',
        ),
    ]
