# Generated by Django 6.1.1 on 2026-09-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_rename_stu_m_stu_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stu_Model',
            new_name='stu_m',
        ),
    ]
