d = {}
name = input("Enter friends name:")
lang = input("Enter the language:")
d.update({name: lang})
name = input("Enter friends name:")
lang = input("Enter the language:")
d.update({name: lang})
name = input("Enter friends name:")
lang = input("Enter the language:")
d.update({name: lang})
name = input("Enter friends name:")
lang = input("Enter the language:")
d.update({name: lang})
print(d)
